name: aisyahh_store
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  firebase_storage: ^12.3.6
  provider: ^6.0.5
  shared_preferences: ^2.0.15
  image_picker: ^1.1.2
  google_sign_in: ^6.2.2
  http: ^0.13.3
  midtrans_sdk: ^0.4.0
  qr_flutter: ^4.1.0
  pdf: ^3.10.6
  printing: ^5.11.0
  js: ^0.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
